image: ubuntu1804

build: off

install:
  - sudo apt install -y software-properties-common
  - sudo add-apt-repository ppa:avsm/ppa
  - sudo apt install opam -y
  - ./build.sh
  - eval $(opam env)

test_script:
  - make test
